
#   Peticion get para obtener todos los administradors.
#   Debe enviarse por el HEADER el fk_institucion al que queremos consultar los administradors.
#   Se debe especificar en por parametro el estado ( 0 => Inactivo(Borrado) o 1 => ACTIVO ) que queremos obtener.
GET http://localhost:8080/api/administradores?estado=0 HTTP/1.1
fk_institucion: 1

###

# Peticion get para obtener un administrador.
GET http://localhost:8080/api/administradores?id=4&estado=1 HTTP/1.1
fk_institucion: 1

###

# Peticion post para crear un usuario.
# Parametros opcionales
# imagen
# estado: 0 o 1
# Se debe enviar por el header el rol_admin para saber que el que esta haciendo la consulta es un administrador.
POST http://localhost:8080/api/administradores HTTP/1.1 
Content-Type: application/json
fk_institucion: 1
rol_admin: 0

{
    "cedula": "0000000000",
    "nombre": "Admin0",
    "apellidos": "0Admin",
    "fecha_nacimiento": "2001-08-09",
    "genero": "M",
    "email": "admin0@gmail.com",
    "clave": "123456",
    "telefono": "",
    "celular": "00000000",
    "direccion": "Calle 1 # 1 - 1",
    "fk_institucion": "1",
    "tipo_usuario": 0,
    "rol": 1
}

###

# Peticion put para actualizar un administrador.
# Se le envian los datos que se quieren modificar.
# Recomendable enviar todo el objeto.
# PUT http://localhost:8080/api/usuarios/id_a_modificar
# Se le envia por el HEADER el rol_admin para saber que el que esta haciendo la consulta es un administrador.
PUT http://localhost:8080/api/administradores/4 HTTP/1.1
Content-Type: application/json
fk_institucion: 1
rol_admin: 0

{
    "estado": 1
}

###

# Peticion delete para eliminar un usuario.
# DELETE http://localhost:8080/api/usuarios/id_a_eliminar
# Se le envia por el HEADER el tipo de usuario que hace la peticion.
DELETE http://localhost:8080/api/administradores/1 HTTP/1.1
Content-Type: application/json
fk_institucion: 1
tipo_usuario: 0
